@startuml

interface Shape1 {
    + area(): int
}

class Circle1 {
    - r: int
    + area(): int
}

class Square1 {
    - height: int
    + area(): int
}

Shape1 <|.. Circle1
Shape1 <|.. Square1

class Book {
    - title: String
    - author: String
    - price: double
}

class BookPrinter {
    + print(book: Book): void
}

class PriceCalculator {
    + calculatePrice(book: Book): double
}

BookPrinter ..> Book
PriceCalculator ..> Book

@enduml